docs_dir: "content"
site_name: "FraudBusters | docs"
#repo_url: https://github.com/valitydev/fraudo
#edit_uri: ""
theme:
  name: gitbook
  highlightjs: true
  icon:
    logo: material/alpha-e-box
  favicon: assets/favicon.ico
  language: ru
  features:
    - toc.integrate
  palette:
    primary: teal
    accent: teal

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  nav:
    sort_order: reverse
strict: false

plugins:
  - autolinks

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - smarty
  - admonition
  - def_list
  - footnotes
  - codehilite
  - attr_list
  - md_in_html
  - meta
  - toc:
      permalink: false

nav:
  - О продукте: "index.md"
  - Быстрый старт:
      - Пробная версия: "docs/free-version.md"
      - Простой сценарий использования: "docs/simple-use-case.md"
      - Первичная настройка системы: "docs/simple-config.md"
      - Комерческая поддержка от vality: "docs/vality-support.md"
  - Для разработчиков:
      - Архитектура: "docs/architecture.md"
      - Протоколы взаимодействия: "docs/api.md"
      - Community: "docs/community.md"
  - Для офицеров безопасности:
      - Аналитика: "docs/use-fraud-analytics.md"
      - Язык: "docs/use-fraud-language.md"
      - Тестирование: "docs/use-fraud-tests.md"
  - Release Notes:
        - 01.02.2017: "docs/use-fraud-language.md"